version: "3"
services:
  frontend:
    image: frontend
    build:
      context: ./front/
      dockerfile: Dockerfile
    ports:
      - '80:80' # - 띄어쓰기
      - '443:443'
    volumes:
      - /home/ubuntu/docker-volume/ssl/:/var/www/html
    container_name: frontend

  server:
    image: backend
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - '8443:8443'
    container_name: backend
    