# Generated by Django 3.2.13 on 2022-05-03 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('profile_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('profile_img', models.TextField()),
            ],
            options={
                'db_table': 'profile_image',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word_level', models.SmallIntegerField()),
                ('word', models.TextField()),
            ],
            options={
                'db_table': 'words',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rank',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('winner_user_id', models.BigIntegerField()),
                ('loser_user_id', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match',
            },
        ),
    ]
