# Generated by Django 3.2.13 on 2022-05-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
